/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



uint8_t current_task=1;

uint32_t g_tick_count=0;

const uint32_t const_v_1 =100;
const uint32_t const_v_2 =100;
const uint8_t const_v_3 =100;



typedef struct {
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t	 current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];
extern void initialise_monitor_handles(void);

int main(void)
{
	enable_processor_faults();

   	init_scheduler_stack(SCHED_STACK_START);
	initialise_monitor_handles();

	printf("implementation of simple task scheduler\n");

	init_task_stack();
	led_init_all();
	init_systick_timer(TICK_HZ);
	led_init_all();
	 switch_sp_to_psp();
	  task1_handler();
	 /* Loop forever */
	for(;;);
}

void task1_handler(void){
	while(1){
		printf("task1 is executing\n");
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler(void){
	while(1){
		printf("task2 is executing\n");
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task3_handler(void){
	while(1){
		printf("task3 is executing\n");
		led_on(LED_RED);
		task_delay(250);
		led_off(LED_RED);
		task_delay(250);
	}
}

void task4_handler(void){
	while(1){
		printf("task4 is executing\n");
		led_on(LED_BLUE);
		task_delay(125);
		led_off(LED_BLUE);
		task_delay(125);
	}
}


void init_systick_timer(uint32_t Tick_hz){


	uint32_t countvalue =(SYSTICK_TIM_CLK/Tick_hz)-1;
	uint32_t *pSRVR=(uint32_t *)0xE000E014;
	uint32_t *pSCSR=(uint32_t *)0xE000E010;
	//clear the value of SVR
	*pSRVR &=~(0x00FFFFFF);
	// load the value in to SVR
	*pSRVR |=countvalue;

	// do some settings
	*pSCSR |=(1<<1);// enable systick exception request;
	*pSCSR |=(1<<2);// indicates the clock soucre,PROCESSOR CLOCK SOURCE
	// enable the systick
	*pSCSR |=(1<<0);// enables the counter
}

void init_task_stack(void){

	user_tasks[0].current_state =TASK_READY_STATE;
	user_tasks[1].current_state =TASK_READY_STATE;
	user_tasks[2].current_state =TASK_READY_STATE;
	user_tasks[3].current_state =TASK_READY_STATE;
	user_tasks[4].current_state =TASK_READY_STATE;

	user_tasks[0].psp_value =IDLE_STACK_START;
	user_tasks[1].psp_value =T1_STACK_START;
	user_tasks[2].psp_value =T2_STACK_START;
	user_tasks[3].psp_value =T3_STACK_START;
	user_tasks[4].psp_value =T4_STACK_START;

	user_tasks[0].task_handler =idle_tasks;
	user_tasks[1].task_handler =task1_handler;
	user_tasks[2].task_handler =task2_handler;
	user_tasks[3].task_handler =task3_handler;
	user_tasks[4].task_handler =task4_handler;


	uint32_t *pPSP;
	for(int i=0; i < MAX_TASKS ;i++){
		pPSP=(uint32_t *)user_tasks[i].psp_value;
		pPSP--;
		*pPSP=DUMMY_XPSP;// 0x0100000
		pPSP--;//pc
		*pPSP=(uint32_t)user_tasks[i].task_handler;
		pPSP--;//lr
		*pPSP=0xFFFFFFFD;
		for(int j=0;j<13;j++){
			pPSP--;
			*pPSP=0;
		}
		user_tasks[i].psp_value=(uint32_t)pPSP;
	}
}

void enable_processor_faults(void){
	uint32_t *pSHCSR=(uint32_t *)0xE000ED24;
	*pSHCSR |=(1<<16);//MemManage
	*pSHCSR |=(1<<17);//BusFault
	*pSHCSR |=(1<<18);//"UsageFault

}

void HardFault_Handler(void)
{
    printf("HardFault_Handler\n");
    while (1);
}

void MemManage_Handler(void)
{
    printf("MemManage_Handler\n");
    while (1);
}

void BusFault_Handler(void)
{
   printf("BusFault_Handler\n");
    while (1);
}

void UsageFault_Handler(void)
{

    printf("UsageFault_Handler\n");


    while (1);
}

void save_psp_value(uint32_t current_psp_value){
	user_tasks[current_task].psp_value=current_psp_value;
}
void update_next_task(void){
	int state=TASK_BLOCKED_STATE;
	for(int i=0;i<MAX_TASKS;i++){
	current_task++;
	current_task %=MAX_TASKS;
	state=user_tasks[current_task].current_state;
	if((state==TASK_READY_STATE) && (current_task!=0))
		break;
	}
	if(state !=TASK_READY_STATE)
		current_task=0;
}
uint32_t get_psp_value(void){
	return user_tasks[current_task].psp_value;
}
__attribute__((naked)) void switch_sp_to_psp(void){

	//1.Initialise the psp with task1 stack start address
	__asm volatile("PUSH {LR}");
	// get the value of psp with TASK1 stack start address
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0");// initialise psp
	__asm volatile("POP {LR}");//pop the LR value
	//2.change sp to psp using CONTROL register
	__asm volatile("MOV R0 ,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}

__attribute__((naked)) void PendSV_Handler(void){
/*save the context of current task*/
	//1.get current runnig task's psp value
	__asm volatile("MRS R0,PSP");
	//2. using that psp value store sf2(R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");
	__asm volatile("PUSH {LR}");
	// save the current value psp
	__asm volatile("BL save_psp_value");

//retreieve the context of next task
	//1.decide next task tpo run
	__asm volatile("BL update_next_task");
	//2. get its past psp value
	__asm volatile("BL get_psp_value");
	//3. using that psp value retrive sf2(R4 to R11)
	__asm volatile("LDMIA R0!,{R4-R11}");
	//4.update psp to exit
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");

}

void update_global_tick_count(void){
	g_tick_count++;
}

void unblock_tasks(void){

	for(int i=1;i<MAX_TASKS;i++){
		if(user_tasks[i].current_state !=TASK_READY_STATE){
			if(user_tasks[i].block_count==g_tick_count){
				user_tasks[i].current_state=TASK_READY_STATE;

			}
		}
	}
}
void SysTick_Handler(void){

	uint32_t *pICSR = (uint32_t *)0xE000ED04;
	update_global_tick_count();
	unblock_tasks();
	*pICSR |=(1<<28);

}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){
	__asm volatile("MSR MSP,%0": : "r"(sched_top_of_stack)  :  );
	__asm volatile("BX LR");
}

void task_delay(uint32_t tick_count){

	// disable interrupt
	INTERRUPT_DISABLE();
	if(current_task){
	user_tasks[current_task].block_count=g_tick_count + tick_count;
	user_tasks[current_task].current_state=TASK_BLOCKED_STATE;
	schedule();
	}
	INTERRUPT_ENABLE();
}

void idle_tasks(void){
	while(1);
}

void schedule(void){

	uint32_t *pICSR =(uint32_t*)0xE000ED04;
	*pICSR |=(1<<28);

}

